{
 "title": "Fabric-X-Committer Performance Dashboard",
 "tags": [ "prometheus" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "sig_verifier_instance",
    "label": "Sig Verifier Servers",
    "query": {
     "query": "sc_component_type{component=\"sigverifier\"}"
    }
   },
   {
    "name": "coordinator_instance",
    "label": "Coordinator Servers",
    "query": {
     "query": "sc_component_type{component=\"coordinator\"}"
    }
   },
   {
    "name": "shards_service_instance",
    "label": "Shard Servers",
    "query": {
     "query": "sc_component_type{component=\"shards-service\"}"
    }
   },
   {
    "name": "generator_instance",
    "label": "Generator Servers",
    "query": {
     "query": "sc_component_type{component=\"generator\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Generator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(loadgen_transaction_received_total[10s])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(loadgen_transaction_sent_total[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99%-Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(loadgen_valid_transaction_latency_seconds_bucket[$__interval]))",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "histogram_quantile(0.99, rate(loadgen_invalid_transaction_latency_seconds_bucket[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Coordinator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Transaction Received Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(coordinator_grpc_received_transaction_total[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (Valid and Invalid Txs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expression": "$A + $B + $C + $D", "type": "math" }
   ]
  },
  {
   "title": "Throughput (Committed Tx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(coordinator_grpc_committed_transaction_total[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (Invalid Tx: Signature)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "targets": [
    {
     "expr": "rate(coordinator_grpc_sent_transaction_invalid_signature_status_total[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (Invalid Tx: Duplicate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "rate(coordinator_grpc_sent_transaction_duplicate_tx_status_total[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (Invalid Tx: MVCC Conflicts)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
   "targets": [
    {
     "expr": "rate(coordinator_grpc_sent_transaction_mvcc_conflict_status_total[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Signature Verifier Manager Queue Sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "coordinator_sigverifier_input_block_queue_size",
     "legendFormat": "__auto"
    },
    {
     "expr": "coordinator_sigverifier_output_valid_block_queue_size",
     "legendFormat": "__auto"
    },
    {
     "expr": "coordinator_sigverifier_output_invalid_block_queue_size",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dependency Graph Manager Queue Sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "targets": [
    {
     "expr": "coordinator_local_dependency_graph_input_tx_batch_queue_size",
     "legendFormat": "__auto"
    },
    {
     "expr": "coordinator_global_dependency_graph_input_tx_batch_queue_size",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator/Committer Manager Queue Sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "expr": "coordinator_vcservice_input_tx_batch_queue_size",
     "legendFormat": "__auto"
    },
    {
     "expr": "coordinator_vcservice_output_validated_tx_batch_queue_size",
     "legendFormat": "__auto"
    },
    {
     "expr": "coordinator_vcservice_output_tx_status_batch_queue_size",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dependency Graph Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "coordinator_global_dependency_graph_size",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (Signature Verifier)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(coordinator_sigverifier_transaction_processed_total[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (Local Dependency Graph)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(coordinator_local_dependency_graph_tx_processed_total[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (Global Dependency Graph)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(coordinator_global_dependency_graph_tx_processed_total[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (Global Dependency Graph - Post Validation)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(coordinator_global_dependency_graph_validated_tx_processed_total[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (VC Service)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(coordinator_vcservice_transaction_processed_total[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Global Dependency Graph -- ConstructDependencyGraph()",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "(rate(coordinator_global_dependency_graph_construction_seconds_sum[10s])) / rate(coordinator_global_dependency_graph_construction_seconds_count[10s]) * 1000",
     "legendFormat": "ConstructDependencyGraph"
    },
    {
     "expr": "rate(coordinator_global_dependency_graph_constructor_wait_for_lock_seconds_sum[10s]) * 1000 / rate(coordinator_global_dependency_graph_constructor_wait_for_lock_seconds_count[10s])",
     "legendFormat": "Waiting For Lock"
    },
    {
     "expr": "(rate(coordinator_global_dependency_graph_add_tx_batch_to_graph_seconds_sum[10s]) * 1000) / rate(coordinator_global_dependency_graph_add_tx_batch_to_graph_seconds_count[10s])",
     "legendFormat": "Add Tx Batch To Graph"
    },
    {
     "expr": "(rate(coordinator_global_dependency_graph_update_dependency_detector_seconds_sum[10s]) * 1000) / rate(coordinator_global_dependency_graph_update_dependency_detector_seconds_count[10s])",
     "legendFormat": "Add Tx Batch to Dependency Detector"
    }
   ]
  },
  {
   "title": "Global Dependency Graph - ProcessValidatedTransactions()",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "(rate(coordinator_global_dependency_graph_validated_tx_batch_processing_seconds_sum[10s]) * 1000) / rate(coordinator_global_dependency_graph_validated_tx_batch_processing_seconds_count[10s])",
     "legendFormat": "ProcessValidatedTx"
    },
    {
     "expr": "(rate(coordinator_global_dependency_graph_validated_tx_batch_processor_wait_for_lock_seconds_sum[10s]) * 1000) / rate(coordinator_global_dependency_graph_validated_tx_batch_processor_wait_for_lock_seconds_count[10s])",
     "legendFormat": "Waiting For Lock"
    },
    {
     "expr": "(rate(coordinator_global_dependency_graph_remove_dependents_of_validated_tx_batch_seconds_sum[10s]) * 1000) / rate(coordinator_global_dependency_graph_remove_dependents_of_validated_tx_batch_seconds_count[10s])",
     "legendFormat": "Remove Dependents and Find Freed Txs"
    },
    {
     "expr": "(rate(coordinator_global_dependency_graph_add_freed_tx_batch_seconds_sum[10s]) * 1000) / rate(coordinator_global_dependency_graph_add_freed_tx_batch_seconds_count[10s])",
     "legendFormat": "Add Freed Transactions"
    }
   ]
  },
  {
   "title": "CPU Basic (System & User)",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (instance) (sum by (instance, cpu) (rate(node_cpu_seconds_total{mode=~\"user|system\", job=\"coordinators\"}[$__interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{ job=\"coordinators\" }",
     "legendFormat": "RAM Total ({{instance}})"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"coordinators\"} - node_memory_MemFree_bytes{job=\"coordinators\"} - (node_memory_Cached_bytes{job=\"coordinators\"} + node_memory_Buffers_bytes{job=\"coordinators\"} + node_memory_SReclaimable_bytes{job=\"coordinators\"})",
     "legendFormat": "RAM Used ({{instance}})"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_network_receive_bytes_total{ job=\"coordinators\" }[$__interval])) * 8",
     "legendFormat": "recv {{device}} ({{instance}})"
    },
    {
     "expr": "sum by (instance) (rate(node_network_transmit_bytes_total{job=\"coordinators\"}[$__interval])) * 8",
     "legendFormat": "trans {{device}}  ({{instance}})"
    }
   ]
  },
  {
   "title": "I/O Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total[$__interval])",
     "legendFormat": "{{device}} ({{instance}})"
    }
   ]
  },
  {
   "title": "VCService",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Throughput (RPS*)",
     "type": "timeseries",
     "description": "If the TX consists of multiple SNs (e.g. 4), it will be most probably split into different shards (e.g. 2 shards will get each 1 SN and 1 shard will get 2). It will count as one TX for each shard and that will give a false total of 3 TXs instead of 1.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(instance) (rate(vcservice_committed_transaction_total[$__interval]))",
       "legendFormat": "In ({{instance}})"
      }
     ]
    },
    {
     "title": "CPU Basic (System & User)",
     "type": "timeseries",
     "description": "Basic CPU info",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by (instance) (sum by (instance, cpu) (rate(node_cpu_seconds_total{mode=~\"user|system\",instance=~\"$shards_service_instance:.+\"}[$__interval])))\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Basic",
     "type": "timeseries",
     "description": "Basic memory usage",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$shards_service_instance:.+\"}",
       "legendFormat": "RAM Total ({{instance}})"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$shards_service_instance:.+\"} - node_memory_MemFree_bytes{instance=~\"$shards_service_instance:.+\"} - (node_memory_Cached_bytes{instance=~\"$shards_service_instance:.+\"} + node_memory_Buffers_bytes{instance=~\"$shards_service_instance:.+\"} + node_memory_SReclaimable_bytes{instance=~\"$shards_service_instance:.+\"})",
       "legendFormat": "RAM Used ({{instance}})"
      }
     ]
    },
    {
     "title": "Network Traffic Basic",
     "type": "timeseries",
     "description": "Basic network info per interface",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(node_network_receive_bytes_total{instance=~\"$shards_service_instance:.+\"}[$__interval]))*8",
       "legendFormat": "recv {{device}} ({{instance}})"
      },
      {
       "expr": "sum by (instance) (rate(node_network_transmit_bytes_total{instance=~\"$shards_service_instance:.+\"}[$__interval]))*8",
       "legendFormat": "trans {{device}}  ({{instance}})"
      }
     ]
    },
    {
     "title": "I/O Utilization",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$shards_service_instance:.+\"} [$__interval])",
       "legendFormat": "{{device}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Channel-Buffer Utilisation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
     "targets": [
      {
       "expr": "sc_channel_length{component=\"shards-service\"}",
       "legendFormat": "{{sub_component}} > {{channel}}"
      }
     ]
    },
    {
     "title": "Go Routines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
     "targets": [
      {
       "expr": "sc_go_routines{component=\"shards-service\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Shard DB read/write 99%-Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, rate(sc_shard_db_read_latency_bucket[$__interval]))",
       "legendFormat": "{{instance}} - Read"
      },
      {
       "expr": "histogram_quantile(0.95, rate(sc_shard_db_write_latency_bucket[$__interval])) * -1",
       "legendFormat": "{{instance}} - Write"
      }
     ]
    },
    {
     "title": "Shard sizes (committed Serial numbers)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 147 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sc_component_throughput{component=\"shards-service\", direction=\"out\"}",
       "legendFormat": "Shard {{sub_component}}"
      }
     ]
    },
    {
     "title": "Data structure sizes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 147 },
     "targets": [
      {
       "expr": "sc_data_structure_size{component=\"shards-service\"}",
       "legendFormat": "{{sub_component}} > {{prop}}"
      }
     ]
    }
   ]
  },
  { "title": "Sig Verifier", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "Total Throughput (TPS)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(sc_component_throughput{instance=~\"$sig_verifier_instance:.+\",sub_component=\"verifier_server\",direction=\"in\"}[$__interval]))",
     "legendFormat": "In ({{instance}})"
    },
    {
     "expr": "sum by (instance) (-1 * rate(sc_component_throughput{instance=~\"$sig_verifier_instance:.+\",sub_component=\"verifier_server\",direction=\"out\"}[$__interval]))",
     "legendFormat": "Out ({{instance}})"
    }
   ]
  },
  {
   "title": "Active Streams",
   "type": "gauge",
   "description": "How many clients have an open stream to the server",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sc_active_streams", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "99%-Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(sc_sigverifier_latency_bucket[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Basic (System & User)",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (instance) (sum by (instance, cpu) (rate(node_cpu_seconds_total{mode=~\"user|system\"}[$__interval])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$sig_verifier_instance:.+\"}",
     "legendFormat": "RAM Total ({{instance}})"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$sig_verifier_instance:.+\"} - node_memory_MemFree_bytes{instance=~\"$sig_verifier_instance:.+\"} - (node_memory_Cached_bytes{instance=~\"$sig_verifier_instance:.+\"} + node_memory_Buffers_bytes{instance=~\"$sig_verifier_instance:.+\"} + node_memory_SReclaimable_bytes{instance=~\"$sig_verifier_instance:.+\"})",
     "legendFormat": "RAM Used ({{instance}})"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_network_receive_bytes_total{instance=~\"$sig_verifier_instance:.+\"}[$__interval]))*8",
     "legendFormat": "recv {{device}} ({{instance}})"
    },
    {
     "expr": "sum by (instance) (rate(node_network_transmit_bytes_total{instance=~\"$sig_verifier_instance:.+\"}[$__interval]))*8",
     "legendFormat": "trans {{device}}  ({{instance}})"
    }
   ]
  },
  {
   "title": "I/O Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$sig_verifier_instance:.+\"} [$__interval])",
     "legendFormat": "{{device}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Channel-Buffer Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
   "targets": [
    {
     "expr": "sc_channel_length{component=\"sigverifier\"}",
     "legendFormat": "{{sub_component}} > {{channel}}"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 140 },
   "targets": [
    {
     "expr": "sc_go_routines{component=\"sigverifier\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Detailed Throughput (TPS)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(sc_component_throughput{component=\"sigverifier\", direction=\"in\"}[$__interval])",
     "legendFormat": "In {{sub_component}} ({{instance}})"
    },
    {
     "expr": "rate(sc_component_throughput{component=\"sigverifier\", direction=\"out\"}[30s]) * -1",
     "legendFormat": "Out {{sub_component}} ({{instance}})"
    }
   ]
  }
 ]
}