/*
Copyright IBM Corp. All Rights Reserved.

SPDX-License-Identifier: Apache-2.0
*/

package loadgen

import (
	"github.com/hyperledger/fabric-x-committer/loadgen/adapters"
	"github.com/hyperledger/fabric-x-committer/loadgen/metrics"
	"github.com/hyperledger/fabric-x-committer/loadgen/workload"
	"github.com/hyperledger/fabric-x-committer/utils/connection"
)

type (
	// ClientConfig is a struct that contains the configuration for the client.
	ClientConfig struct {
		// Server for a gRPC server for the full load-generator's gRPC API.
		Server *connection.ServerConfig `mapstructure:"server"`
		// HTTPServer for an HTTP server to set/get the limiter's rate.
		HTTPServer *connection.ServerConfig `mapstructure:"http-server"`
		Monitoring metrics.Config           `mapstructure:"monitoring" yaml:"monitoring"`

		Adapter     adapters.AdapterConfig  `mapstructure:",squash" yaml:",inline"`
		Stream      *workload.StreamOptions `mapstructure:"stream" yaml:"stream"`
		LoadProfile *workload.Profile       `mapstructure:"load-profile" yaml:"load-profile"`
		Limit       *adapters.GenerateLimit `mapstructure:"limit" yaml:"limit"`

		// Generate If omitted, all phases will be generated by default.
		Generate adapters.Phases `mapstructure:"generate" yaml:"generate"`
	}
)
