# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
---
server:
  endpoint: :7050
  tls:
    # TLS configuration being built based on the tls mode chosen: none, tls, mtls.
    mode: mtls
    cert-path: /root/artifacts/ordererOrganizations/orderer-org-0/orderers/orderer-0-org-0/tls/server.crt
    key-path: /root/artifacts/ordererOrganizations/orderer-org-0/orderers/orderer-0-org-0/tls/server.key
    ca-cert-paths:
      - /root/artifacts/peerOrganizations/peer-org-0/users/client@peer-org-0.com/tls/ca.crt

block-size: 1024
block-timeout: 30s
send-genesis-block: true
artifacts-path: /root/artifacts

logging:
  logSpec: "info"
  format: >-
    %{color}%{time:2006-01-02 15:04:05.000 MST} [%{module}] %{shortfunc}
    -> %{level:.4s}%{color:reset} %{message}

