// Code generated by MockGen. DO NOT EDIT.
// Source: delivery.go
//
// Generated by this command:
//
//	mockgen -source=delivery.go -destination=streamer_mock_test.go -package=deliver_test
//

// Package deliver_test is a generated GoMock package.
package deliver_test

import (
	context "context"
	reflect "reflect"

	common "github.com/hyperledger/fabric-protos-go-apiv2/common"
	deliver "github.com/hyperledger/fabric-x-committer/utils/deliver"
	gomock "go.uber.org/mock/gomock"
)

// MockDeliverer is a mock of Deliverer interface.
type MockDeliverer struct {
	ctrl     *gomock.Controller
	recorder *MockDelivererMockRecorder
	isgomock struct{}
}

// MockDelivererMockRecorder is the mock recorder for MockDeliverer.
type MockDelivererMockRecorder struct {
	mock *MockDeliverer
}

// NewMockDeliverer creates a new mock instance.
func NewMockDeliverer(ctrl *gomock.Controller) *MockDeliverer {
	mock := &MockDeliverer{ctrl: ctrl}
	mock.recorder = &MockDelivererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliverer) EXPECT() *MockDelivererMockRecorder {
	return m.recorder
}

// Deliver mocks base method.
func (m *MockDeliverer) Deliver(ctx context.Context) (deliver.Streamer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deliver", ctx)
	ret0, _ := ret[0].(deliver.Streamer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Deliver indicates an expected call of Deliver.
func (mr *MockDelivererMockRecorder) Deliver(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deliver", reflect.TypeOf((*MockDeliverer)(nil).Deliver), ctx)
}

// MockStreamer is a mock of Streamer interface.
type MockStreamer struct {
	ctrl     *gomock.Controller
	recorder *MockStreamerMockRecorder
	isgomock struct{}
}

// MockStreamerMockRecorder is the mock recorder for MockStreamer.
type MockStreamerMockRecorder struct {
	mock *MockStreamer
}

// NewMockStreamer creates a new mock instance.
func NewMockStreamer(ctrl *gomock.Controller) *MockStreamer {
	mock := &MockStreamer{ctrl: ctrl}
	mock.recorder = &MockStreamerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamer) EXPECT() *MockStreamerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockStreamer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockStreamerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockStreamer)(nil).Context))
}

// RecvBlockOrStatus mocks base method.
func (m *MockStreamer) RecvBlockOrStatus() (*common.Block, *common.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecvBlockOrStatus")
	ret0, _ := ret[0].(*common.Block)
	ret1, _ := ret[1].(*common.Status)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RecvBlockOrStatus indicates an expected call of RecvBlockOrStatus.
func (mr *MockStreamerMockRecorder) RecvBlockOrStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvBlockOrStatus", reflect.TypeOf((*MockStreamer)(nil).RecvBlockOrStatus))
}

// Send mocks base method.
func (m *MockStreamer) Send(arg0 *common.Envelope) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockStreamerMockRecorder) Send(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockStreamer)(nil).Send), arg0)
}
