#!/usr/bin/env bash
#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
set -euo pipefail

PATH="bin:${PATH}"

runHelp() {
  local command="$1"
  $command --help 2>&1 | sed -E 's/[[:space:]]+$//g'
}

generateHelpText() {
  local DOC="$1"
  shift

  cat <<'HEADER' > "$DOC"
<!---
 SPDX-License-Identifier: Apache-2.0
 File generated by help_docs.sh. DO NOT EDIT.
 Re-run scripts/help_docs.sh generate to update.
 --->

HEADER

  cat <<'PREAMBLE' >> "$DOC"
# committer

The `committer` command starts Fabric-X committer services and checks service health.

PREAMBLE

  local code_delim='```'
  local commands=("$@")
  for x in "${commands[@]}" ; do
    cat <<EOD >> "$DOC"

## $x
$code_delim
$(runHelp "$x")
$code_delim

EOD
  done
}

checkHelpTextCurrent() {
  local doc="$1"
  shift

  local tempfile
  tempfile="$(mktemp -t "$(basename "$doc")".XXXXX)" || exit 1

  generateHelpText "$tempfile" "$@"
  if ! diff -u "$doc" "$tempfile"; then
    rm -f "$tempfile"
    echo "The command line help docs are out of date and need to be regenerated. Run scripts/help_docs.sh generate."
    exit 2
  fi

  rm -f "$tempfile"
}

generateOrCheck() {
  if [[ "$action" == "generate" ]]; then
    generateHelpText "$@"
  elif [[ "$action" == "check" ]]; then
    checkHelpTextCurrent "$@"
  else
    echo "usage: $0 [generate|check]" >&2
    exit 1
  fi
}

action="${1:-generate}"

commands=(
  "committer"
  "committer start"
  "committer start sidecar"
  "committer start coordinator"
  "committer start verifier"
  "committer start vc"
  "committer start query"
  "committer healthcheck"
  "committer healthcheck sidecar"
  "committer healthcheck coordinator"
  "committer healthcheck verifier"
  "committer healthcheck vc"
  "committer healthcheck query"
  "committer version"
)
generateOrCheck \
  docs/cli/committer.md \
  "${commands[@]}"
