//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/servicepb/vcservice.proto

package servicepb

import (
	applicationpb "github.com/hyperledger/fabric-x-common/api/applicationpb"
	committerpb "github.com/hyperledger/fabric-x-common/api/committerpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VcBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*VcTx                `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VcBatch) Reset() {
	*x = VcBatch{}
	mi := &file_api_servicepb_vcservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VcBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VcBatch) ProtoMessage() {}

func (x *VcBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_servicepb_vcservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VcBatch.ProtoReflect.Descriptor instead.
func (*VcBatch) Descriptor() ([]byte, []int) {
	return file_api_servicepb_vcservice_proto_rawDescGZIP(), []int{0}
}

func (x *VcBatch) GetTransactions() []*VcTx {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type VcTx struct {
	state                 protoimpl.MessageState       `protogen:"open.v1"`
	Ref                   *committerpb.TxRef           `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Namespaces            []*applicationpb.TxNamespace `protobuf:"bytes,2,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	PrelimInvalidTxStatus *committerpb.Status          `protobuf:"varint,3,opt,name=prelim_invalid_tx_status,json=prelimInvalidTxStatus,proto3,enum=committerpb.Status,oneof" json:"prelim_invalid_tx_status,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *VcTx) Reset() {
	*x = VcTx{}
	mi := &file_api_servicepb_vcservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VcTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VcTx) ProtoMessage() {}

func (x *VcTx) ProtoReflect() protoreflect.Message {
	mi := &file_api_servicepb_vcservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VcTx.ProtoReflect.Descriptor instead.
func (*VcTx) Descriptor() ([]byte, []int) {
	return file_api_servicepb_vcservice_proto_rawDescGZIP(), []int{1}
}

func (x *VcTx) GetRef() *committerpb.TxRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *VcTx) GetNamespaces() []*applicationpb.TxNamespace {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *VcTx) GetPrelimInvalidTxStatus() committerpb.Status {
	if x != nil && x.PrelimInvalidTxStatus != nil {
		return *x.PrelimInvalidTxStatus
	}
	return committerpb.Status(0)
}

// SnapshotTxIDRequest carries only a snapshot tx_id. Shared by
// OwnsSnapshotHashJob and RestartSnapshotHash, which both take only a tx_id
// (never a caller-supplied clone_database — both RPCs re-read the current
// _snapshot row/worker state for the given tx_id internally).
type SnapshotTxIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxId          string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotTxIDRequest) Reset() {
	*x = SnapshotTxIDRequest{}
	mi := &file_api_servicepb_vcservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotTxIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotTxIDRequest) ProtoMessage() {}

func (x *SnapshotTxIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_servicepb_vcservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotTxIDRequest.ProtoReflect.Descriptor instead.
func (*SnapshotTxIDRequest) Descriptor() ([]byte, []int) {
	return file_api_servicepb_vcservice_proto_rawDescGZIP(), []int{2}
}

func (x *SnapshotTxIDRequest) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

var File_api_servicepb_vcservice_proto protoreflect.FileDescriptor

const file_api_servicepb_vcservice_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/servicepb/vcservice.proto\x12\tservicepb\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a api/applicationpb/block_tx.proto\x1a\x1eapi/applicationpb/config.proto\x1a\x1capi/committerpb/status.proto\x1a\x19api/committerpb/ref.proto\x1a\x1eapi/committerpb/snapshot.proto\x1a\x1aapi/servicepb/common.proto\">\n" +
	"\aVcBatch\x123\n" +
	"\ftransactions\x18\x01 \x03(\v2\x0f.servicepb.VcTxR\ftransactions\"\xd8\x01\n" +
	"\x04VcTx\x12$\n" +
	"\x03ref\x18\x01 \x01(\v2\x12.committerpb.TxRefR\x03ref\x12:\n" +
	"\n" +
	"namespaces\x18\x02 \x03(\v2\x1a.applicationpb.TxNamespaceR\n" +
	"namespaces\x12Q\n" +
	"\x18prelim_invalid_tx_status\x18\x03 \x01(\x0e2\x13.committerpb.StatusH\x00R\x15prelimInvalidTxStatus\x88\x01\x01B\x1b\n" +
	"\x19_prelim_invalid_tx_status\"*\n" +
	"\x13SnapshotTxIDRequest\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId2\xf9\x05\n" +
	"\x1aValidationAndCommitService\x12R\n" +
	"\x1cStartValidateAndCommitStream\x12\x12.servicepb.VcBatch\x1a\x1a.committerpb.TxStatusBatch(\x010\x01\x12L\n" +
	"\x1bSetLastCommittedBlockNumber\x12\x13.servicepb.BlockRef\x1a\x16.google.protobuf.Empty\"\x00\x12K\n" +
	"\x1aGetNextBlockNumberToCommit\x12\x16.google.protobuf.Empty\x1a\x13.servicepb.BlockRef\"\x00\x12N\n" +
	"\x15GetTransactionsStatus\x12\x17.committerpb.TxIDsBatch\x1a\x1a.committerpb.TxStatusBatch\"\x00\x12R\n" +
	"\x14GetNamespacePolicies\x12\x16.google.protobuf.Empty\x1a .applicationpb.NamespacePolicies\"\x00\x12R\n" +
	"\x14GetConfigTransaction\x12\x16.google.protobuf.Empty\x1a .applicationpb.ConfigTransaction\"\x00\x12N\n" +
	"\x16GetLatestSnapshotState\x12\x16.google.protobuf.Empty\x1a\x1a.committerpb.SnapshotState\"\x00\x12S\n" +
	"\x13OwnsSnapshotHashJob\x12\x1e.servicepb.SnapshotTxIDRequest\x1a\x1a.google.protobuf.BoolValue\"\x00\x12O\n" +
	"\x13RestartSnapshotHash\x12\x1e.servicepb.SnapshotTxIDRequest\x1a\x16.google.protobuf.Empty\"\x00B9Z7github.com/hyperledger/fabric-x-committer/api/servicepbb\x06proto3"

var (
	file_api_servicepb_vcservice_proto_rawDescOnce sync.Once
	file_api_servicepb_vcservice_proto_rawDescData []byte
)

func file_api_servicepb_vcservice_proto_rawDescGZIP() []byte {
	file_api_servicepb_vcservice_proto_rawDescOnce.Do(func() {
		file_api_servicepb_vcservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_servicepb_vcservice_proto_rawDesc), len(file_api_servicepb_vcservice_proto_rawDesc)))
	})
	return file_api_servicepb_vcservice_proto_rawDescData
}

var file_api_servicepb_vcservice_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_servicepb_vcservice_proto_goTypes = []any{
	(*VcBatch)(nil),                         // 0: servicepb.VcBatch
	(*VcTx)(nil),                            // 1: servicepb.VcTx
	(*SnapshotTxIDRequest)(nil),             // 2: servicepb.SnapshotTxIDRequest
	(*committerpb.TxRef)(nil),               // 3: committerpb.TxRef
	(*applicationpb.TxNamespace)(nil),       // 4: applicationpb.TxNamespace
	(committerpb.Status)(0),                 // 5: committerpb.Status
	(*BlockRef)(nil),                        // 6: servicepb.BlockRef
	(*emptypb.Empty)(nil),                   // 7: google.protobuf.Empty
	(*committerpb.TxIDsBatch)(nil),          // 8: committerpb.TxIDsBatch
	(*committerpb.TxStatusBatch)(nil),       // 9: committerpb.TxStatusBatch
	(*applicationpb.NamespacePolicies)(nil), // 10: applicationpb.NamespacePolicies
	(*applicationpb.ConfigTransaction)(nil), // 11: applicationpb.ConfigTransaction
	(*committerpb.SnapshotState)(nil),       // 12: committerpb.SnapshotState
	(*wrapperspb.BoolValue)(nil),            // 13: google.protobuf.BoolValue
}
var file_api_servicepb_vcservice_proto_depIdxs = []int32{
	1,  // 0: servicepb.VcBatch.transactions:type_name -> servicepb.VcTx
	3,  // 1: servicepb.VcTx.ref:type_name -> committerpb.TxRef
	4,  // 2: servicepb.VcTx.namespaces:type_name -> applicationpb.TxNamespace
	5,  // 3: servicepb.VcTx.prelim_invalid_tx_status:type_name -> committerpb.Status
	0,  // 4: servicepb.ValidationAndCommitService.StartValidateAndCommitStream:input_type -> servicepb.VcBatch
	6,  // 5: servicepb.ValidationAndCommitService.SetLastCommittedBlockNumber:input_type -> servicepb.BlockRef
	7,  // 6: servicepb.ValidationAndCommitService.GetNextBlockNumberToCommit:input_type -> google.protobuf.Empty
	8,  // 7: servicepb.ValidationAndCommitService.GetTransactionsStatus:input_type -> committerpb.TxIDsBatch
	7,  // 8: servicepb.ValidationAndCommitService.GetNamespacePolicies:input_type -> google.protobuf.Empty
	7,  // 9: servicepb.ValidationAndCommitService.GetConfigTransaction:input_type -> google.protobuf.Empty
	7,  // 10: servicepb.ValidationAndCommitService.GetLatestSnapshotState:input_type -> google.protobuf.Empty
	2,  // 11: servicepb.ValidationAndCommitService.OwnsSnapshotHashJob:input_type -> servicepb.SnapshotTxIDRequest
	2,  // 12: servicepb.ValidationAndCommitService.RestartSnapshotHash:input_type -> servicepb.SnapshotTxIDRequest
	9,  // 13: servicepb.ValidationAndCommitService.StartValidateAndCommitStream:output_type -> committerpb.TxStatusBatch
	7,  // 14: servicepb.ValidationAndCommitService.SetLastCommittedBlockNumber:output_type -> google.protobuf.Empty
	6,  // 15: servicepb.ValidationAndCommitService.GetNextBlockNumberToCommit:output_type -> servicepb.BlockRef
	9,  // 16: servicepb.ValidationAndCommitService.GetTransactionsStatus:output_type -> committerpb.TxStatusBatch
	10, // 17: servicepb.ValidationAndCommitService.GetNamespacePolicies:output_type -> applicationpb.NamespacePolicies
	11, // 18: servicepb.ValidationAndCommitService.GetConfigTransaction:output_type -> applicationpb.ConfigTransaction
	12, // 19: servicepb.ValidationAndCommitService.GetLatestSnapshotState:output_type -> committerpb.SnapshotState
	13, // 20: servicepb.ValidationAndCommitService.OwnsSnapshotHashJob:output_type -> google.protobuf.BoolValue
	7,  // 21: servicepb.ValidationAndCommitService.RestartSnapshotHash:output_type -> google.protobuf.Empty
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_servicepb_vcservice_proto_init() }
func file_api_servicepb_vcservice_proto_init() {
	if File_api_servicepb_vcservice_proto != nil {
		return
	}
	file_api_servicepb_common_proto_init()
	file_api_servicepb_vcservice_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_servicepb_vcservice_proto_rawDesc), len(file_api_servicepb_vcservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_servicepb_vcservice_proto_goTypes,
		DependencyIndexes: file_api_servicepb_vcservice_proto_depIdxs,
		MessageInfos:      file_api_servicepb_vcservice_proto_msgTypes,
	}.Build()
	File_api_servicepb_vcservice_proto = out.File
	file_api_servicepb_vcservice_proto_goTypes = nil
	file_api_servicepb_vcservice_proto_depIdxs = nil
}
