//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/serializationpb/channel_header.proto

package serializationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EnvelopeLiteProto is a projection of common.Envelope.
type EnvelopeLiteProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvelopeLiteProto) Reset() {
	*x = EnvelopeLiteProto{}
	mi := &file_api_serializationpb_channel_header_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvelopeLiteProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvelopeLiteProto) ProtoMessage() {}

func (x *EnvelopeLiteProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_serializationpb_channel_header_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvelopeLiteProto.ProtoReflect.Descriptor instead.
func (*EnvelopeLiteProto) Descriptor() ([]byte, []int) {
	return file_api_serializationpb_channel_header_proto_rawDescGZIP(), []int{0}
}

func (x *EnvelopeLiteProto) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// PayloadLite is a projection of common.Payload.
type PayloadLite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        []byte                 `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadLite) Reset() {
	*x = PayloadLite{}
	mi := &file_api_serializationpb_channel_header_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadLite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadLite) ProtoMessage() {}

func (x *PayloadLite) ProtoReflect() protoreflect.Message {
	mi := &file_api_serializationpb_channel_header_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadLite.ProtoReflect.Descriptor instead.
func (*PayloadLite) Descriptor() ([]byte, []int) {
	return file_api_serializationpb_channel_header_proto_rawDescGZIP(), []int{1}
}

func (x *PayloadLite) GetHeader() []byte {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PayloadLite) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// HeaderLite is a projection of common.Header.
type HeaderLite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelHeader []byte                 `protobuf:"bytes,1,opt,name=channel_header,json=channelHeader,proto3" json:"channel_header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderLite) Reset() {
	*x = HeaderLite{}
	mi := &file_api_serializationpb_channel_header_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderLite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderLite) ProtoMessage() {}

func (x *HeaderLite) ProtoReflect() protoreflect.Message {
	mi := &file_api_serializationpb_channel_header_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderLite.ProtoReflect.Descriptor instead.
func (*HeaderLite) Descriptor() ([]byte, []int) {
	return file_api_serializationpb_channel_header_proto_rawDescGZIP(), []int{2}
}

func (x *HeaderLite) GetChannelHeader() []byte {
	if x != nil {
		return x.ChannelHeader
	}
	return nil
}

// ChannelHeaderLite is a projection of common.ChannelHeader.
type ChannelHeaderLite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	TxId          string                 `protobuf:"bytes,5,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelHeaderLite) Reset() {
	*x = ChannelHeaderLite{}
	mi := &file_api_serializationpb_channel_header_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelHeaderLite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelHeaderLite) ProtoMessage() {}

func (x *ChannelHeaderLite) ProtoReflect() protoreflect.Message {
	mi := &file_api_serializationpb_channel_header_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelHeaderLite.ProtoReflect.Descriptor instead.
func (*ChannelHeaderLite) Descriptor() ([]byte, []int) {
	return file_api_serializationpb_channel_header_proto_rawDescGZIP(), []int{3}
}

func (x *ChannelHeaderLite) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ChannelHeaderLite) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

var File_api_serializationpb_channel_header_proto protoreflect.FileDescriptor

const file_api_serializationpb_channel_header_proto_rawDesc = "" +
	"\n" +
	"(api/serializationpb/channel_header.proto\x12\x0fserializationpb\"-\n" +
	"\x11EnvelopeLiteProto\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"9\n" +
	"\vPayloadLite\x12\x16\n" +
	"\x06header\x18\x01 \x01(\fR\x06header\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"3\n" +
	"\n" +
	"HeaderLite\x12%\n" +
	"\x0echannel_header\x18\x01 \x01(\fR\rchannelHeader\"<\n" +
	"\x11ChannelHeaderLite\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x13\n" +
	"\x05tx_id\x18\x05 \x01(\tR\x04txIdB?Z=github.com/hyperledger/fabric-x-committer/api/serializationpbb\x06proto3"

var (
	file_api_serializationpb_channel_header_proto_rawDescOnce sync.Once
	file_api_serializationpb_channel_header_proto_rawDescData []byte
)

func file_api_serializationpb_channel_header_proto_rawDescGZIP() []byte {
	file_api_serializationpb_channel_header_proto_rawDescOnce.Do(func() {
		file_api_serializationpb_channel_header_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_serializationpb_channel_header_proto_rawDesc), len(file_api_serializationpb_channel_header_proto_rawDesc)))
	})
	return file_api_serializationpb_channel_header_proto_rawDescData
}

var file_api_serializationpb_channel_header_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_serializationpb_channel_header_proto_goTypes = []any{
	(*EnvelopeLiteProto)(nil), // 0: serializationpb.EnvelopeLiteProto
	(*PayloadLite)(nil),       // 1: serializationpb.PayloadLite
	(*HeaderLite)(nil),        // 2: serializationpb.HeaderLite
	(*ChannelHeaderLite)(nil), // 3: serializationpb.ChannelHeaderLite
}
var file_api_serializationpb_channel_header_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_serializationpb_channel_header_proto_init() }
func file_api_serializationpb_channel_header_proto_init() {
	if File_api_serializationpb_channel_header_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_serializationpb_channel_header_proto_rawDesc), len(file_api_serializationpb_channel_header_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_serializationpb_channel_header_proto_goTypes,
		DependencyIndexes: file_api_serializationpb_channel_header_proto_depIdxs,
		MessageInfos:      file_api_serializationpb_channel_header_proto_msgTypes,
	}.Build()
	File_api_serializationpb_channel_header_proto = out.File
	file_api_serializationpb_channel_header_proto_goTypes = nil
	file_api_serializationpb_channel_header_proto_depIdxs = nil
}
